#region Copyright
////////////////////////////////////////////////////////////////////////////////
// The following FIT Protocol software provided may be used with FIT protocol
// devices only and remains the copyrighted property of Dynastream Innovations Inc.
// The software is being provided on an "as-is" basis and as an accommodation,
// and therefore all warranties, representations, or guarantees of any kind
// (whether express, implied or statutory) including, without limitation,
// warranties of merchantability, non-infringement, or fitness for a particular
// purpose, are specifically disclaimed.
//
// Copyright 2014 Dynastream Innovations Inc.
////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 12.20Release
// Tag = $Name$
////////////////////////////////////////////////////////////////////////////////

#endregion

namespace FitFilePreviewer.Decode.Fit.Mesgs
{
   /// <summary>
   /// Implements the Pad profile message.
   /// </summary>  
   public class PadMesg : Mesg 
   {    
      #region Fields     
      #endregion

      #region Constructors                 
      public PadMesg() : base((Mesg) Profile.mesgs[Profile.PadIndex])               
      {                 
      }
      
      public PadMesg(Mesg mesg) : base(mesg)
      {
      }
      #endregion // Constructors

      #region Methods                  
      #endregion // Methods
   } // Class
} // namespace
